openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-throttle-key: $bf_capture_account_id
x-bc-upstream: 'http://backend_server'
info:
  title: Brightcove Interactivity API Reference
  description: |- 
    API for videocloud to access interactivity data. To test API requests, you can use our <a href="/getting-started/concepts-testing-tools-brightcove-apis.html" target="_blank">API Testing Tools</a>.

    For additional in-depth guides to features of the API, see the **[general documentation](/interactivity/index.html)**.

    **Base URL**: https://interactivity.api.brightcove.com
  version: 1.0.115-e554f8e
  x-bc-studio: interactivity
servers:
  - url: 'https://interactivity.api.brightcove.com' 
paths:
  '/v1/accounts/{account_id}/projects':
    get:
      summary: Gets all projects for a specific account
      description: Gets all projects for a specific account. It will return the first 10 projects by default.
      tags:
        - Projects
      operationId: GetProjects
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create a project for a specific account
      description: Create a project for a specific account
      tags:
        - Projects
      operationId: CreateProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/counts':
    get:
      summary: Gets the number of projects for a specific account
      description: Gets the number of projects for a specific account
      tags:
        - Projects
      operationId: GetProjectCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/projects/{id}':
    get:
      summary: Gets a specific project from a specific account
      description: Gets a specific project from a specific account
      tags:
        - Projects
      operationId: GetProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: Update an specific project from a specific account
      description: Update an specific project from a specific account
      tags:
        - Projects
      operationId: UpdateProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/{soft_delete}':
    delete:
      summary: Deletes a specific project from a specific account
      description: Deletes a specific project from a specific account. Performs a soft delete by default. Use the request body to perform a hard delete.
      tags:
        - Projects
      operationId: DeleteProject
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/annotations':
    get:
      summary: Gets all annotations for a specific project
      description: Gets all annotations for a specific project
      tags:
        - Project Annotations
      operationId: GetProjectAnnotations
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create an annotation for a project
      description: Create an annotation for a project
      tags:
        - Project Annotations
      operationId: CreateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/projects/{id}/annotations/{annotation_id}':
    get:
      summary: Gets a specific annotation for a specific project
      description: Gets a specific annotation for a specific project
      tags:
        - Project Annotations
      operationId: GetAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: Update an annotation
      description: Update an annotation
      tags:
        - Project Annotations
      operationId: UpdateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: Delete an annotation
      description: Delete an annotation
      tags:
        - Project Annotations
      operationId: DeleteAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates':
    get:
      summary: Gets all templates for a specific account
      description: Gets all templates for a specific account. It will return the first 10 templates by default.
      tags:
        - Templates
      operationId: GetTemplates
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create a template for an account
      description: Create a template for an account
      tags:
        - Templates
      operationId: CreateTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/counts':
    get:
      summary: Gets the count of templates for a specific account
      description: Gets the count of templates for a specific account
      tags:
        - Templates
      operationId: GetTemplateCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/templates/{id}':
    get:
      summary: Gets a specific template for an account
      description: Gets a specific template for an account
      tags:
        - Templates
      operationId: GetTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: Update the template
      description: Update the template
      tags:
        - Templates
      operationId: UpdateTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all 
  '/v1/accounts/{account_id}/templates/{id}/{soft_delete}':
    delete:
      summary: Deletes a template
      description: Deletes a template. Performs a soft delete by default. Use the request body to perform a hard delete.
      tags:
        - Templates
      operationId: DeleteTemplate
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/{id}/annotations':
    get:
      summary: Gets all annotations for a specific template
      description: Gets all annotations for a specific template
      tags:
        - Template Annotations
      operationId: GetTemplateAnnotations
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create an annotation for a template
      description: Create an annotation for a template
      tags:
        - Template Annotations
      operationId: CreateTemplateAnnotation
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/templates/{id}/annotations/{annotation_id}':
    get:
      summary: Gets a specific annotation for a specific template
      description: Gets a specific annotation for a specific template
      tags:
        - Template Annotations
      operationId: GetTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: Update an annotation
      description: Update an annotation
      tags:
        - Template Annotations
      operationId: UpdateTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: Delete an annotation
      description: Delete an annotation
      tags:
        - Template Annotations
      operationId: DeleteTemplateAnnotationById
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences':
    get:
      summary: Gets all experiences for a specific account
      description: Gets all experiences for a specific account
      tags:
        - Experiences
      operationId: GetExperiences
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create a experience for an account
      description: Create a experience for an account
      tags:
        - Experiences
      operationId: CreateExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences/counts':
    get:
      summary: Gets the count of experiences for a specific account
      description: Gets the count of experiences for a specific account
      tags:
        - Experiences
      operationId: GetExperienceCount
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/experiences/{id}':
    get:
      summary: Gets a specific experience for an account
      description: Gets a specific experience for an account
      tags:
        - Experiences
      operationId: GetExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    patch:
      summary: Update the experience
      description: Update the experience
      tags:
        - Experiences
      operationId: UpdateExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all   
  '/v1/accounts/{account_id}/experiences/{id}/{soft_delete}': 
    delete:
      summary: Deletes an experience
      description: Deletes an experience. Performs a soft delete by default. Use the request body to perform a hard delete.
      tags:
        - Experiences
      operationId: DeleteExperience
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/experiences/{id}/scorm_download':
    get:
      summary: Gets scorm download
      description: Gets scorm zip file for an experience
      tags:
        - Experiences
      operationId: GetExperienceScormDownload
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
  '/v1/accounts/{account_id}/folders':
    get:
      summary: Gets all folders for a specific account
      description: Gets all folders for a specific account
      tags:
        - Folders
      operationId: GetFolders
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/read
    post:
      summary: Create a folder for an account
      description: Create a folder for an account
      tags:
        - Folders
      operationId: CreateFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}':
    get:
      summary: Gets a specific folder for an account
      description: Gets a specific folder for an account
      tags:
        - Folders
      operationId: GetFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    patch:
      summary: Rename a folder
      description: Rename a folder
      tags:
        - Folders
      operationId: RenameFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: Delete a folder
      description: Delete a folder
      tags:
        - Folders
      operationId: DeleteFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents':
    get:
      summary: Gets the contents for a specific folder for an account
      description: Gets the contents for a specific folder for an account
      tags:
        - Folders
      operationId: GetFolderContents
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents/counts':
    get:
      summary: Gets the number of content items in a specific folder for an account
      description: Gets the number of content items for a specific folder for an account
      tags:
        - Folders
      operationId: GetFolderContentsCounts
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/folders/{id}/contents/{content_id}':
    put:
      summary: Moves a content item to a folder
      description: Moves a content item to a specific folder for an account
      tags:
        - Folders
      operationId: MoveContentToFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
    delete:
      summary: Removes a content item from a folder
      description: Removes a content item from a specific folder for an account
      tags:
        - Folders
      operationId: RemoveContentFromFolder
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/gradebook/summary':
    get:
      summary: Gets gradebook summary report
      description: Gets counts of correctly answered questions grouped by user id
      tags:
        - Reports
      operationId: GetGradeBookSummary
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/gradebook/users/answers':
    get:
      summary: Gets gradebook user answer details report
      description: Get user submitted answers
      tags:
        - Reports
      operationId: GetGradeBookDetails
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/quiz/actions':
    get:
      summary: Gets quiz actions report
      description: Gets counts of answered questions grouped by project
      tags:
        - Reports
      operationId: GetQuizActions
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
  '/v1/accounts/{account_id}/reports/quiz/project/summary':
    get:
      summary: Gets quiz project summary report
      description: Gets counts of unique answers submitted grouped by question and answer
      tags:
        - Reports
      operationId: GetQuizActionsSummary
      security:
        - BC_OAuth2:
            - video-cloud/interactivity/all
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: 'Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api) or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token) to learn more'
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/interactivity/read: Read
            video-cloud/interactivity/all: All