openapi: '3.0.0'
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'https://mrss_config_server'
info:
  description: |-
    The Syndication Configuration API allows you to create, manage, and retrieve MRSS feeds generated from your Video Cloud video library.

    **Base URL: 'https://social.api.brightcove.com/v1'**
  version: 1.0.0
  title: Brightcove Syndication Configuration API
  x-bc-access: public
servers:
  - url: 'https://social.api.brightcove.com/v1'
    variables: {}
tags:
  - name: OTT Syndications
    description: Operations creating and managing ingest profiles.
paths:
  '/accounts/{account_id}/mrss/ott-syndications':
    post:
      tags:
        - OTT Syndications
      summary: Create a new OTT syndication
      description: >-
        Creates a new OTT syndication.
      operationId: postOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Syndications
      summary: Get all OTT syndications
      description: >-
        Gets a list of all OTT syndications currently configured for the account.
      operationId: getOTTSyndications
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-syndications/{syndication_id}':
    put:
      tags:
        - OTT Syndications
      summary: Update an OTT syndication
      description: >-
        Updates the configuration data for a syndication.  A fully populated OTTSyndication object should be passed as the request body.  Read-only fields can be omitted, and will be ignored if they are included.  Note that the *type* property cannot be changed from the value specified when the syndication was created.
      operationId: putOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    patch:
      tags:
        - OTT Syndications
      summary: Update an OTT syndication
      description: >-
        Updates the configuration data for a syndication.  An OTTSyndication object specifying non-null values for writable fields to be updated should be passed as the request body.  Note that the *type* property cannot be changed from the value specified when the syndication was created.
      operationId: patchOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    delete:
      tags:
        - OTT Syndications
      summary: Delete an OTT syndication
      description: >-
        Deletes an OTT syndication.
      operationId: deleteOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Syndications
      summary: Get an OTT syndication
      description: >-
        Gets the configuration data for an OTT syndication.
      operationId: getOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-syndications/{syndication_id}/template':
    put:
      tags:
        - OTT Templates
      summary: Upload a custom OTT feed template
      description: >-
        Uploads a custom OTT feed template to a universal syndication.
      operationId: putOTTTemplate
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Templates
      summary: Get a custom OTT feed template
      description: >-
        Gets a universal syndication's custom OTT feed template.
      operationId: getOTTTemplate
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-async-jobs':
    post:
      tags:
        - OTT Syndications
      summary: Create a new OTT async job request
      description: >-
        Create a new job request for the asynchronous generation of feeds for one or more OTT Syndications.
      operationId: postOTTAsyncJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Syndications
      summary: Get all OTT Syndications
      description: >-
        Gets a list of all recent OTT Syndications for the account.  Note that jobs expire after 24 hours and will no longer be returned by this method after that.
      operationId: getOTTAsyncJobs
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-async-jobs/{job_id}':
    get:
      tags:
        - OTT Syndications
      summary: Get an OTT async job
      description: >-
        Gets the configuration data for an OTT async job.  Note that jobs expire after 24 hours and will no longer be returned by this method after that.
      operationId: getOTTAsyncJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: >-
        Brightcove OAuth API. See the [support documentation](/oauth/) or [Getting Access Tokens](/oauth/guides/getting-access-tokens.html) to learn more
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/social/mrss/read: Read MRSS feed configuration data
            video-cloud/social/mrss/write: Write MRSS feed configuration data
