openapi: '3.0.0'
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'https://mrss_config_server'
info:
  description: Syndication Configuration API
  version: 1.0.0
  title: Brightcove Syndication Configuration API
  x-bc-access: public
servers:
  - url: 'https://social.api.brightcove.com/v1'
    variables: {}
tags:
  - name: OTT Syndications
    description: 'These operations manage syndication configurations. The actual syndication files are generated and managed using the OTT stored job requests listed next.'
  - name: OTT Stored Jobs
    description: >-
      Stored job operations are used to generate OTT syndications from syndication configurations asynchronously (because depending on how much content you want indexed for universal search, the resulting file may be very large and take some time to generate and send back). Stored jobs can be run manually as needed and can also be configured to run automatically at scheduled intervals.
  - name: OTT Templates
    description: The operations are for managing custom templates for syndications.
paths:
  '/accounts/{account_id}/mrss/ott-syndications':
    post:
      tags:
        - OTT Syndications
      summary: Create a new OTT syndication
      description: >-
        Creates a new OTT syndication.
      operationId: postOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Syndications
      summary: Get all OTT syndications
      description: >-
        Gets a list of all OTT syndications currently configured for the account.
      operationId: getOTTSyndications
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-syndications/{syndication_id}':
    put:
      tags:
        - OTT Syndications
      summary: Update an OTT syndication.
      description: >-
        Updates the configuration data for a syndication.  A fully populated OTTSyndication object should be passed as the request body.  Read-only fields can be omitted, and will be ignored if they are included.  Note that the *type* property cannot be changed from the value specified when the syndication was created.
      operationId: putOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    patch:
      tags:
        - OTT Syndications
      summary: Update an OTT syndication.
      description: >-
        Updates the configuration data for a syndication.  An OTTSyndication object specifying non-null values for writable fields to be updated should be passed as the request body.  Note that the *type* property cannot be changed from the value specified when the syndication was created.
      operationId: patchOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    delete:
      tags:
        - OTT Syndications
      summary: Delete an OTT syndication
      description: >-
        Deletes an OTT syndication.
      operationId: deleteOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Syndications
      summary: Get an OTT syndication
      description: >-
        Gets the configuration data for an OTT syndication.
      operationId: getOTTSyndication
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-syndications/{syndication_id}/template':
    put:
      tags:
        - OTT Templates
      summary: Upload a custom OTT feed template
      description: >-
        Uploads a custom OTT feed template to a universal syndication.
      operationId: putOTTTemplate
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Templates
      summary: Get a custom OTT feed template
      description: >-
        Gets a universal syndication's custom OTT feed template.
      operationId: getOTTTemplate
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-stored-jobs':
    post:
      tags:
        - OTT Stored Jobs
      summary: Create a new OTT stored job.
      description: >-
        Creates a new stored job that can be used for the asynchronous generation of feeds for one or more OTT Syndications.  The stored job can be run manually as needed via the run API method defined below, and can also be configured to automatically run periodically. 
      operationId: postOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    get:
      tags:
        - OTT Stored Jobs
      summary: Get all OTT stored jobs.
      description: >-
        Gets a list of all OTT stored jobs for the account.
      operationId: getOTTStoredJobs
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
  '/accounts/{account_id}/mrss/ott-stored-jobs/{job_id}':
    get:
      tags:
        - OTT Stored Jobs
      summary: Get an OTT stored job
      description: >-
        Gets the configuration data for a specific OTT stored job.
      operationId: getOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/read
    put:
      tags:
        - OTT Stored Jobs
      summary: Update an OTT stored job.
      description: >-
        Updates the configuration data for a stored job.  A fully populated OTTStoredJob object should be passed as the request body.
      operationId: putOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    patch:
      tags:
        - OTT Stored Jobs
      summary: Update an OTT stored job.
      description: >-
        Updates the configuration data for a stored job.  An OTTStoredJob object specifying non-null values for writable fields to be updated should be passed as the request body.
      operationId: patchOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
    delete:
      tags:
        - OTT Stored Jobs
      summary: Delete an OTT stored job
      description: >-
        Deletes an OTT stored job.
      operationId: deleteOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
  '/accounts/{account_id}/mrss/ott-stored-jobs/{job_id}/run':
    post:
      tags:
        - OTT Stored Jobs
      summary: Run an OTT stored job.
      description: >-
        Request an asynchronous execution of a stored job.  No POST body is required.  If the job is already in a PENDING or PROCESSING state the request is ignored.  Call the API GET method for the job id to check the execution status and obtain the result URLs after execution is complete.  Newly generated results will overwrite previously generated results for the job.
      operationId: runOTTStoredJob
      security:
        - BC_OAuth2:
            - video-cloud/social/mrss/write
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: >-
        Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api) or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token) to learn more
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/social/mrss/read: Read MRSS feed configuration data
            video-cloud/social/mrss/write: Write MRSS feed configuration data
