openapi: 3.0.0
info:
  description: This is a service that allows applying Concurrency mid-stream checks without
    DRM
  title: Concurrency Service API
  contact: {}
  version: "1.0"
paths:
  "/accounts/{account_id}/sessions":
    get:
      description: An endpoint that returns active sessions by viewerID
      tags:
        - Session
      summary: GetActiveSessions endpoint
      parameters:
        - description: Account ID
          name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Active Sessions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/model.Session"
        "401":
          description: Unauthorized due to invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/model.ErrorResponse"
    post:
      security:
        - JWTAuth: []
      description: An endpoint that allows or denies playback based on concurrency
        restrictions
      tags:
        - Session
      summary: Session endpoint
      parameters:
        - description: Account ID
          name: account_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/model.HeartbeatRequest"
        description: Heartbeat Request
        required: true
      responses:
        "200":
          description: Playback allowed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/model.HeartbeatResponse"
        "204":
          description: Feature not available for the account
        "401":
          description: Unauthorized due to invalid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/model.ErrorResponse"
        "403":
          description: Forbidden playback due to concurrency limit
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/model.ErrorResponse"
  "/accounts/{account_id}/sessions/{session_id}":
    delete:
      security:
        - JWTAuth: []
      description: An endpoint that removes an active session by AccountID and SessionID
      tags:
        - Session
      summary: StopSession endpoint
      parameters:
        - description: Account ID
          name: account_id
          in: path
          required: true
          schema:
            type: string
        - description: Session ID
          name: session_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Successful delete
        "401":
          description: Unauthorized due to invalid token
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/model.ErrorResponse"
tags:
  - description: Heartbeat related endpoints
    name: Heartbeat
servers:
  - url: http://localhost:8080/api/v1
  - url: https://localhost:8080/api/v1
components:
  securitySchemes:
    JWTAuth:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    model.ErrorDetails:
      type: object
      properties:
        code:
          type: string
          example: ACCESS_DENIED
        message:
          type: string
          example: Video not available.
    model.ErrorResponse:
      type: object
      properties:
        error:
          $ref: "#/components/schemas/model.ErrorDetails"
    model.HeartbeatRequest:
      type: object
      properties:
        sid:
          type: string
        video:
          type: string
    model.HeartbeatResponse:
      type: object
      properties:
        current:
          type: integer
        heartbeat_interval:
          type: integer
        max:
          type: integer
    model.Session:
      type: object
      properties:
        end_viewer_id:
          type: string
        last_seen:
          type: string
        session_id:
          type: string
        stopped:
          type: boolean