openapi: 3.0.0
info:
  title: Source for Channel Manager API Reference
  description: 'Reference for the Brightcove Cloud Playout Channel Manager API, used to access and manage your Cloud Playout channels.'
  version: 1.0.0
  x-bc-access: public
components:
  parameters:
    AccountId:
      name: account_id
      in: path
      description: Video Cloud account ID.
      required: true
      style: simple
      explode: false
      schema:
        type: string
    ContentType:
      name: Content-Type
      in: header
      description: 'Content-Type: application/json'
      required: true
      style: simple
      explode: false
      schema:
        type: string
        default: application/json
    VideoId:
      name: video_id
      in: path
      description: Video ID.
      required: true
      style: simple
      explode: false
      schema:
        type: string
  responses:
    '204':
      description: Item was deleted
      content: {}
    '401':
      description: >-
        UNAUTHORIZED: Authentication failed; check to make sure your client credentials were correct for the access token
      content: {}
    '403':
      description: 'BAD_VALUE: Spelling error or other use of non-existent field '
      content: {}
    '404':
      description: >-
        RESOURCE_NOT_FOUND: The api could not find the resource you requested
      content: {}
    '405':
      description: >-
        METHOD_NOT_ALLOWED: The HTTP method specified is not allowed for this endpoint
      content: {}
    '429':
      description: >-
        TOO_MANY_REQUESTS: You are submitting too many simultaneous requests or too many requests per second
      content: {}
