openapi: 3.0.0
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'http://backend_server'
info:
  title: Program Scheduler API
  version: "1.0"
  description: |-
    Reference for the Brightcove EPG Scheduling Backend API, used to access and manage your EPG schedules. To test API requests, you can use our [API Testing Tools](/getting-started/concepts-testing-tools-brightcove-apis.html). For permissions needed for OAuth credentials, see [API Operations](/oauth/guides/api-operations-client-credentials-requests.html). For information on authenticating API requests, see the [OAuth Overview](/oauth/getting-started/overview-oauth-api-v4.html).

    **Base URL**: https://showtime.api.brightcove.com
  x-bc-access: public
servers:
  - url: https://showtime.api.brightcove.com/v1
    description: The Showtime API server in QA with OAuth.
tags:
  - name: Program service
    description: API for managing EPG programs.
  - name: Schedule service
    description: API for managing EPG schedules.
  - name: Slot service
    description: API for managing EPG slots.
paths:
  /accounts/{account_id}/programs:
    post:
      tags:
        - Program service
      summary: Create program
      description: Creates a new program along with a draft and a main schedule
      operationId: createProgram
      security:
        - BC_OAuth2:
            - video-cloud/schedule/create
  /accounts/{account_id}/programs/{program_id}/actions:
    post:
      tags:
        - Program service
      summary: Program Actions
      description: This Endpoint is intended to run special actions such as publish, copy slots, move slots
      operationId: postAction
      security:
        - BC_OAuth2:
            - video-cloud/schedule/create
  /accounts/{account_id}/schedules:
    get:
      tags:
        - Schedule service
      summary: Get Schedules
      description: Get a paginated list of schedules for an account
      operationId: getSchedules
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
    post:
      tags:
        - Schedule service
      summary: Create Schedule
      description: Create a new Schedule for an account
      operationId: createSchedule
      security:
        - BC_OAuth2:
            - video-cloud/schedule/create
  /accounts/{account_id}/schedules/{schedule_id}/slots:
    get:
      tags:
        - Slot service
      summary: Get Slots
      description: Gets a paginated list of slots for a schedule
      operationId: getScheduleSlots
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
    post:
      tags:
        - Slot service
      summary: Create Slot
      description:  Create a new Slot for a schedule
      operationId: createSlot
      security:
        - BC_OAuth2:
            - video-cloud/schedule/create
    delete:
      tags:
        - Slot service
      summary: Delete Slots
      description: Delete all slots under the schedule
      operationId: deleteAllSlots
      security:
        - BC_OAuth2:
            - video-cloud/schedule/delete
  /accounts/{account_id}/schedules/{schedule_id}:
    get:
      tags:
        - Schedule service
      summary: Get Schedule by ID
      description: Get a schedule by its id
      operationId: getScheduleById
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
    delete:
      tags:
        - Schedule service
      summary: Delete Schedule
      description: Delete a schedule by its id
      operationId: deleteSchedule
      security:
        - BC_OAuth2:
            - video-cloud/schedule/delete
    patch:
      tags:
        - Schedule service
      summary: Update Schedule
      description: Partial update to a schedule
      operationId: updateSchedule
      security:
        - BC_OAuth2:
            - video-cloud/schedule/update
  /accounts/{account_id}/schedules/ref:{reference_id}:
    get:
      tags:
        - Schedule service
      summary: Get Schedule by Reference ID
      description: Get a schedule by its reference id
      operationId: getScheduleByRef
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
    delete:
      tags:
        - Schedule service
      summary: Delete Schedule by Reference ID
      description: Delete a schedule by its reference id
      operationId: deleteScheduleByRef
      security:
        - BC_OAuth2:
            - video-cloud/schedule/delete
    patch:
      tags:
        - Schedule service
      summary: Update Schedule by Reference ID
      description: Partial update to a schedule by its reference id
      operationId: updateScheduleByRef
      security:
        - BC_OAuth2:
            - video-cloud/schedule/update
  /accounts/{account_id}/schedules/{schedule_id}/slots/{slot_id}:
    get:
      tags:
        - Slot service
      summary: Get Slot by ID
      description: Get a slot by its id
      operationId: getSlot
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
    delete:
      tags:
        - Slot service
      summary: Delete Slot
      description: Delete a slot by its id
      operationId: deleteSlot
      security:
        - BC_OAuth2:
            - video-cloud/schedule/delete
    patch:
      tags:
        - Slot service
      summary: Update Slot
      description: Partial update to a slot
      operationId: updateSlot
      security:
        - BC_OAuth2:
            - video-cloud/schedule/update
  /accounts/{account_id}/schedules/{schedule_id}/slots/{slot_ids}:
    delete:
      tags:
        - Slot service
      summary: Delete slots by IDs
      description: Deletes slots by passing a comma separated list of slot ids (up to 10)
      operationId: deleteSlotByIds
      security:
        - BC_OAuth2:
            - video-cloud/schedule/delete
  /accounts/{account_id}/schedules/{schedule_id}/media-references:
    get:
      tags:
        - Schedule service
      summary: Get Slot Media References
      description: Returns a list of customized format slot media references for the given scheduleId, paginated and ordered by start time
      operationId: getScheduleMediaReferences
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
  /accounts/{account_id}/schedules/{schedule_id}/errors:
    get:
      tags:
        - Schedule service
      summary: Check Schedule
      description: Validates a given schedule for slot errors. The scheduleId can be reference_id.
      operationId: checkSchedule
      security:
        - BC_OAuth2:
            - video-cloud/schedule/read
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: "Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api)\
        \ or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token)\
        \ to learn more"
      flows:
        clientCredentials:
          tokenUrl: https://oauth.qa.brightcove.com/v4/access_token
          scopes:
            video-cloud/schedule/read: Read schedule data.
            video-cloud/schedule/create: Create a schedule data.
            video-cloud/schedule/update: Update a schedule data
            video-cloud/schedule/delete: Delete a schedule data.
            video-cloud/schedule/all: Read, write, update and delete schedule data.