openapi: 3.0.3
x-bc-implicit-head: true
x-bc-implicit-options: true
x-bc-upstream: 'https://backend_server'
info:
  title: Brightcove Cloud Playout Channel Manager API Reference
  description: |-
    Reference for the Brightcove Cloud Playout Channel Manager API, used to access and manage your Cloud Playout channels.

    **Base URL: https://cm.cloudplayout.brightcove.com**
  version: 1.0.0
x-bc-access: public
servers:
  - url: 'https://cm.cloudplayout.brightcove.com'
    description: Production server
    variables: {}
tags:
  - name: Channels
    description: >-
      Create and manage Cloud Playout channels.
  - name: Assets
    description: Create and manage static and dynamic overlay assets.
  - name: Channel Static Overlays
    description: Operations related to associating a static overlay with a channel.
  - name: Channel Dynamic Overlays
    description: Operations related to associating a dynamic overlay with a channel.
  - name: Credentials
    description: Operations for creating and managing S3 credentials.
  - name: Profiles
    description: Get the live profiles that a channel can use.
  - name: BC Live channels
    description: Get the Brightcove Live channels (SEP jobs) that a channel can use.
paths:
  '/accounts/{account_id}/cp_channels':
    post:
      tags:
        - Channels
      summary: Create channel
      description: 'Creates a cloud playout channel'
      operationId: CreateChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Channels
      summary: Get all channels for an account
      description: 'Gets all Cloud Playout channels for an account'
      operationId: GetAllChannels
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}':
    get:
      tags:
        - Channels
      summary: Get details of a channel
      description: 'Gets all Cloud Playout channels for an account'
      operationId: GetChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Channels
      summary: Delete a channel
      description: 'Delete a Cloud Playout channel'
      operationId: DeleteChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Channels
      summary: Update a channel
      description: 'Update a Cloud Playout channel'
      operationId: UpdateChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/schedules':
    patch:
      tags:
        - Channels
      summary: Update schedule of a channel
      description: 'Update the schedule (start, stop and hard start time) of a cloud playout channel'
      operationId: UpdateChannelSchedule
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/start':
    post:
      tags:
        - Channels
      summary: Start a channel
      description: 'Start a cloud playout channel'
      operationId: StartChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/stop':
    post:
      tags:
        - Channels
      summary: Stop a channel
      description: 'Stop a cloud playout channel'
      operationId: StopChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/create':
    post:
      tags:
        - Channels
      summary: Activate a channel
      description: 'Activate a cloud playout channel'
      operationId: ActivateChannel
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/preview':
    get:
      tags:
        - Channels
      summary: Get preview of a running channel
      description: 'Get preview image of a running channel'
      operationId: GetChannelPreview
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/telemetrics/healthmetric':
    get:
      tags:
        - Channels
      summary: Get health metrics of a running channel
      description: 'Get health metrics of a running channel'
      operationId: GetChannelMetric
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/as_run_logs':
    get:
      tags:
        - Channels
      summary: Get as run logs of a channel
      description: "Provides an ability to retrieve a log of a prior day's events (in 24-hour UTC time), allowing for auditing of aired content"
      operationId: GetAsRunLogs
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/assets/{asset_type}':
    post:
      tags:
        - Assets
      summary: Create a new cloud playout asset for an account
      description: 'Create a new asset'
      operationId: CreateAsset
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Assets
      summary: Get all cloud playout assets for an account
      description: 'Get all assets'
      operationId: GetAssets
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/assets/{asset_type}/{asset_id}':
    get:
      tags:
        - Assets
      summary: Get a cloud playout asset for an account
      description: 'Get an asset'
      operationId: GetAsset
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Assets
      summary: Delete a cloud playout asset for an account
      description: 'Delete an asset'
      operationId: DeleteAsset
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Assets
      summary: Update a cloud playout asset for an account
      description: 'Update an asset'
      operationId: UpdateAsset
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/video/{video_id}/order/{order}/skip':
    post:
      tags:
        - Play Now
      summary: Skip to a particular asset in a running channel
      description: 'Skip to a particular asset in a running channel'
      operationId: SkipToVideoId
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/overlays':
    post:
      tags:
        - Channel Static Overlays
      summary: Associate a static overlay asset for a channel
      description: 'Associate a static overlay asset for a channel'
      operationId: AssociateOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Channel Static Overlays
      summary: Get All static overlay images for a channel
      description: 'Get All static overlay images for a channel'
      operationId: GetChannelOverlays
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/overlays/{overlay_id}':
    patch:
      tags:
        - Channel Static Overlays
      summary: Update a static overlay asset for a channel
      description: 'Update a static overlay asset for a channel'
      operationId: UpdateAssociatedOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Channel Static Overlays
      summary: Get a static overlay image for a channel
      description: 'Get a static overlay image for a channel'
      operationId: GetChannelOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Channel Static Overlays
      summary: delete a static overlay image for a channel
      description: 'Delete a static overlay image for a channel'
      operationId: DeleteChannelOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/overlays/{overlay_id}/deactivate':
    post:
      tags:
        - Channel Static Overlays
      summary: Deactivate a static overlay asset for a channel
      description: 'Deactivate a static overlay asset for a channel'
      operationId: DeactivateOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/dynamic_overlays':
    post:
      tags:
        - Channel Dynamic Overlays
      summary: Associate a dynamic overlay for a channel
      description: 'Associate a dynamic overlay for a channel'
      operationId: AssociateDynamicOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Channel Dynamic Overlays
      summary: Get All dynamic overlays for a channel
      description: 'Get All dynamic overlays for a channel'
      operationId: GetChannelDynamicOverlays
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/dynamic_overlays/{overlay_id}':
    patch:
      tags:
        - Channel Dynamic Overlays
      summary: Update a dynamic overlay for a channel
      description: 'Update a dynamic overlay for a channel'
      operationId: UpdateAssociatedDynamicOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Channel Dynamic Overlays
      summary: Get a dynamic overlay for a channel
      description: 'Get a dynamic overlay for a channel'
      operationId: GetChannelDynamicOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Channel Dynamic Overlays
      summary: delete a dynamic overlay for a channel
      description: 'Delete a dynamic overlay for a channel'
      operationId: DeleteChannelDynamicOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/cp_channels/{channel_id}/dynamic_overlays/{overlay_id}/deactivate':
    post:
      tags:
        - Channel Dynamic Overlays
      summary: Deactivate a dynamic overlay for a channel
      description: 'Deactivate a dynamic overlay for a channel'
      operationId: DeactivateDynamicOverlay
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/credentials':
    post:
      tags:
        - Credentials
      summary: Create S3 credentials
      description: 'Creates a S3 credential for a channel'
      operationId: CreateCredentials
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    get:
      tags:
        - Credentials
      summary: Get All S3 credentials
      description: 'Get All S3 credentials for an account'
      operationId: GetCredentials
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/credentials/{credential_id}':
    get:
      tags:
        - Credentials
      summary: Get a S3 credential
      description: 'Creates a S3 credential for a channel'
      operationId: GetCredential
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      tags:
        - Credentials
      summary: Update an S3 credential
      description: 'Creates a S3 credential for a channel'
      operationId: UpdateCredential
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      tags:
        - Credentials
      summary: Delete a S3 credential
      description: 'Creates a S3 credential for a channel'
      operationId: DeleteCredential
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/all
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/profiles':
    get:
      tags:
        - Profiles
      summary: List All Live profiles
      description: 'List all Live profiles that a channel can use'
      operationId: ListProfiles
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  '/accounts/{account_id}/bc_channels':
    get:
      tags:
        - BC Live channels
      summary: List All BC Live channels
      description: 'List all BC Live channels that a channel can use'
      operationId: ListBCLiveChannels
      deprecated: false
      security:
        - BC_OAuth2:
            - video-cloud/cloud-playout/read
components:
  securitySchemes:
    BC_OAuth2:
      type: oauth2
      description: 'Brightcove OAuth API. See the [support documentation](https://support.brightcove.com/oauth-api) or [Getting Access Tokens](https://support.brightcove.com/oauth-api-sample-get-access-token) to learn more'
      flows:
        clientCredentials:
          tokenUrl: 'https://oauth.brightcove.com/v4/access_token'
          scopes:
            video-cloud/cloud-playout/all: Able to manage cloud playout channels.
            video-cloud/cloud-playout/read: Able to read cloud playout channels.